FROM quay.io/keycloak/keycloak:20.0.5 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

# Configure themes
WORKDIR /opt/keycloak/themes
RUN mkdir -p ineditta
COPY . /opt/keycloak/themes/ineditta

USER root

RUN chown -R keycloak /opt/keycloak/themes/ineditta

USER keycloak

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:20.0.5 as final
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]