using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ineditta.Repository.Migrations
{
    /// <inheritdoc />
    public partial class v52 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                                    UPDATE jfase jf set fase = '{""fase"":""Assembleia Patronal"",""perguntas"":[{""tipo"":""R"",""texto"":""Contato realizado?"",""opcoes"":[],""adicionais"":[{""tipo"":""S"",""texto"":""Sindicato contatado"",""opcoes"":[""Laboral"",""Patronal""]},{""tipo"":""S"",""texto"":""Contato feito por"",""opcoes"":[""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"":""T"",""texto"":""Houve alteração no status da negociação?"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Em caso de impasse selecione os motivos"",""opcoes"":["" "",""Fechamento do INPC"",""Mandato Diretoria"",""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial"",""Impasse na negociação de cláusulas Econômicas"",""Impasse na negociação de cláusulas sociais"",""Impasse na negociação da cláusula Domingos"",""Impasse na negociação da cláusula Feriados"",""Impasse na negociação da cláusula Contribuição"",""Impasse na negociação da cláusula Banco de Horas"",""Os sindicatos não estão divulgando os impasses da negociação"",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"",""cláusulas em discussão"",""Mandato da diretoria pendente"",""Não há interesse em realizar as negociações por parte do Laboral"",""Não há interesse em realizar as negociações por parte do Patronal"",""Outro""]},{""tipo"":""T"",""texto"":""Caso o motivo seja outro escreva aqui"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Estimativa do reajuste patronal?"",""opcoes"":[]},{""tipo"":""TA"",""texto"":""Observações (Para uso interno da Ineditta)"",""opcoes"":[]}]},{""tipo"":""R"",""texto"":""Há data prevista para assembleia patronal?"",""opcoes"":[],""adicionais"":[{""tipo"":""D"",""texto"":""Data assembléia"",""opcoes"":[]},{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Comentários da assembleia patronal"",""opcoes"":[]}]},{""tipo"":""R"",""texto"":""Há data prevista para reunião entre entidades sindicais?"",""opcoes"":[],""adicionais"":[{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""tipo"":""D"",""texto"":""Data da reunião"",""opcoes"":[]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da reunião entre entidades sindicais"",""opcoes"":[]}]}]}'
                                    WHERE id_jfase = 1;
                                    UPDATE jfase jf set fase = '{""fase"":""Negociação Não Iniciada"",""perguntas"":[{""tipo"":""R"",""texto"":""Contato realizado?"",""opcoes"":[],""adicionais"":[{""tipo"":""S"",""texto"":""Sindicato contatado"",""opcoes"":[""Laboral"",""Patronal""]},{""tipo"":""S"",""texto"":""Contato feito por"",""opcoes"":[""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"":""T"",""texto"":""Houve alteração no status da negociação?"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Em caso de impasse selecione os motivos"",""opcoes"":["" "",""Fechamento do INPC"",""Mandato Diretoria"",""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial"",""Impasse na negociação de cláusulas Econômicas"",""Impasse na negociação de cláusulas sociais"",""Impasse na negociação da cláusula Domingos"",""Impasse na negociação da cláusula Feriados"",""Impasse na negociação da cláusula Contribuição"",""Impasse na negociação da cláusula Banco de Horas"",""Os sindicatos não estão divulgando os impasses da negociação"",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"",""cláusulas em discussão"",""Mandato da diretoria pendente"",""Não há interesse em realizar as negociações por parte do Laboral"",""Não há interesse em realizar as negociações por parte do Patronal"",""Outro""]},{""tipo"":""T"",""texto"":""Caso o motivo seja outro escreva aqui"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Estimativa do reajuste patronal?"",""opcoes"":[]},{""tipo"":""TA"",""texto"":""Observações (Para uso interno da Ineditta)"",""opcoes"":[]}]},{""tipo"":""R"",""texto"":""Há data prevista para assembleia patronal?"",""opcoes"":[],""adicionais"":[{""tipo"":""D"",""texto"":""Data assembléia"",""opcoes"":[]},{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Comentários da assembleia patronal"",""opcoes"":[]}]},{""tipo"":""R"",""texto"":""Há data prevista para reunião entre entidades sindicais?"",""opcoes"":[],""adicionais"":[{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""tipo"":""D"",""texto"":""Data da reunião"",""opcoes"":[]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da reunião entre entidades sindicais"",""opcoes"":[]}]}]}'
                                    WHERE id_jfase = 2;
                                    UPDATE jfase jf set fase = '{""fase"":""Em Negociação"",""perguntas"":[{""tipo"":""R"",""texto"":""Contato realizado?"",""opcoes"":[],""adicionais"":[{""tipo"":""S"",""texto"":""Sindicato contatado"",""opcoes"":[""Laboral"",""Patronal""]},{""tipo"":""S"",""texto"":""Contato feito por"",""opcoes"":[""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"":""T"",""texto"":""Houve alteração no status da negociação?"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Em caso de impasse selecione os motivos"",""opcoes"":["" "",""Fechamento do INPC"",""Mandato Diretoria"",""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial"",""Impasse na negociação de cláusulas Econômicas"",""Impasse na negociação de cláusulas sociais"",""Impasse na negociação da cláusula Domingos"",""Impasse na negociação da cláusula Feriados"",""Impasse na negociação da cláusula Contribuição"",""Impasse na negociação da cláusula Banco de Horas"",""Os sindicatos não estão divulgando os impasses da negociação"",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"",""cláusulas em discussão"",""Mandato da diretoria pendente"",""Não há interesse em realizar as negociações por parte do Laboral"",""Não há interesse em realizar as negociações por parte do Patronal"",""Outro""]},{""tipo"":""T"",""texto"":""Caso o motivo seja outro escreva aqui"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Estimativa do reajuste patronal?"",""opcoes"":[]},{""tipo"":""TA"",""texto"":""Observações (Para uso interno da Ineditta)"",""opcoes"":[]}]},{""tipo"":""R"",""texto"":""Há data prevista para assembleia patronal?"",""opcoes"":[],""adicionais"":[{""tipo"":""D"",""texto"":""Data assembléia"",""opcoes"":[]},{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Comentários da assembleia patronal"",""opcoes"":[]}]},{""tipo"":""R"",""texto"":""Há data prevista para reunião entre entidades sindicais?"",""opcoes"":[],""adicionais"":[{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""tipo"":""D"",""texto"":""Data da reunião"",""opcoes"":[]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da reunião entre entidades sindicais"",""opcoes"":[]}]}]}'
                                    WHERE id_jfase = 3;
            ");

            migrationBuilder.Sql(@"CREATE OR REPLACE VIEW `classe_cnae_vw` AS
                                select
                                    `cct`.`id_cnae` AS `id`,
                                    `cct`.`divisao_cnae` AS `divisao`,
                                    `cct`.`subclasse_cnae` AS `subclasse`,
                                    `cct`.`descricao_subclasse` AS `descricao_subclasse`,
                                    `cct`.`categoria` AS `categoria`,
                                    `sindptr`.`sindicatos` AS `siglas_sindicatos_patronais`,
                                    `sindlbr`.`sindicatos` AS `siglas_sindicatos_laborais`
                                from
                                    ((`classe_cnae` `cct`
                                left join lateral (
                                    select
                                        group_concat(distinct `spt`.`sigla_sp` separator ', ') AS `sindicatos`
                                    from
                                        (`base_territorialsindpatro` `btt`
                                    join `sind_patr` `spt` on
                                        ((`btt`.`sind_patronal_id_sindp` = `spt`.`id_sindp`)))
                                    where
                                        (`btt`.`classe_cnae_idclasse_cnae` = `cct`.`id_cnae`)) `sindptr` on
                                    (true))
                                left join lateral (
                                    select
                                        group_concat(distinct `sett`.`sigla_sinde` separator ', ') AS `sindicatos`
                                    from
                                        (`base_territorialsindemp` `btet`
                                    join `sind_emp` `sett` on
                                        ((`btet`.`sind_empregados_id_sinde1` = `sett`.`id_sinde`)))
                                    where
                                        (`btet`.`classe_cnae_idclasse_cnae` = `cct`.`id_cnae`)) `sindlbr` on
                                    (true));");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                                    UPDATE jfase jf set fase = '{""fase"":""Assembleia Patronal"",""perguntas"":[{""tipo"":""R"",""texto"":""Contato realizado?"",""opcoes"":[],""adicionais"":[{""tipo"":""D"",""texto"":""Data assembléia"",""opcoes"":[]},{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Comentários da assembleia patronal"",""opcoes"":[]}]},{""tipo"":""S"",""texto"":""Sindicato contatado"",""opcoes"":[""Laboral"",""Patronal""]},{""tipo"":""S"",""texto"":""Contato feito por"",""opcoes"":[""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"":""T"",""texto"":""Houve alteração no status da negociação?"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Em caso de impasse selecione os motivos"",""opcoes"":["" "",""Fechamento do INPC"",""Mandato Diretoria"",""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial"",""Impasse na negociação de cláusulas Econômicas"",""Impasse na negociação de cláusulas sociais"",""Impasse na negociação da cláusula Domingos"",""Impasse na negociação da cláusula Feriados"",""Impasse na negociação da cláusula Contribuição"",""Impasse na negociação da cláusula Banco de Horas"",""Os sindicatos não estão divulgando os impasses da negociação"",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"",""cláusulas em discussão"",""Mandato da diretoria pendente"",""Não há interesse em realizar as negociações por parte do Laboral"",""Não há interesse em realizar as negociações por parte do Patronal"",""Outro""]},{""tipo"":""T"",""texto"":""Caso o motivo seja outro escreva aqui"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Estimativa do reajuste patronal?"",""opcoes"":[]},{""tipo"":""TA"",""texto"":""Observações (Para uso interno da Ineditta)"",""opcoes"":[]}]}'
                                    WHERE id_jfase = 1;
                                    UPDATE jfase jf set fase ='{""fase"":""Negociação Não Iniciada"",""perguntas"":[{""tipo"":""R"",""texto"":""Contato realizado?"",""opcoes"":[],""adicionais"":[{""tipo"":""D"",""texto"":""Data assembléia"",""opcoes"":[]},{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Comentários da assembleia patronal"",""opcoes"":[]}]},{""tipo"":""S"",""texto"":""Sindicato contatado"",""opcoes"":[""Laboral"",""Patronal""]},{""tipo"":""S"",""texto"":""Contato feito por"",""opcoes"":[""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"":""T"",""texto"":""Houve alteração no status da negociação?"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Em caso de impasse selecione os motivos"",""opcoes"":["" "",""Fechamento do INPC"",""Mandato Diretoria"",""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial"",""Impasse na negociação de cláusulas Econômicas"",""Impasse na negociação de cláusulas sociais"",""Impasse na negociação da cláusula Domingos"",""Impasse na negociação da cláusula Feriados"",""Impasse na negociação da cláusula Contribuição"",""Impasse na negociação da cláusula Banco de Horas"",""Os sindicatos não estão divulgando os impasses da negociação"",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"",""cláusulas em discussão"",""Mandato da diretoria pendente"",""Não há interesse em realizar as negociações por parte do Laboral"",""Não há interesse em realizar as negociações por parte do Patronal"",""Outro""]},{""tipo"":""T"",""texto"":""Caso o motivo seja outro escreva aqui"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Estimativa do reajuste patronal?"",""opcoes"":[]},{""tipo"":""TA"",""texto"":""Observações (Para uso interno da Ineditta)"",""opcoes"":[]}]}'
                                    WHERE id_jfase = 2;
                                    UPDATE jfase jf set fase ='{""fase"":""Em Negociação"",""perguntas"":[{""tipo"":""R"",""texto"":""Contato realizado?"",""opcoes"":[],""adicionais"":[{""tipo"":""D"",""texto"":""Data assembléia"",""opcoes"":[]},{""tipo"":""S"",""texto"":""Tipo de assembléia"",""opcoes"":[""Presencial"",""Online""]},{""mask"":""00:00"",""tipo"":""T"",""texto"":""Hora da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Endereço da assembleia patronal"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Comentários da assembleia patronal"",""opcoes"":[]}]},{""tipo"":""S"",""texto"":""Sindicato contatado"",""opcoes"":[""Laboral"",""Patronal""]},{""tipo"":""S"",""texto"":""Contato feito por"",""opcoes"":[""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"":""T"",""texto"":""Houve alteração no status da negociação?"",""opcoes"":[]},{""tipo"":""SM"",""texto"":""Em caso de impasse selecione os motivos"",""opcoes"":["" "",""Fechamento do INPC"",""Mandato Diretoria"",""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial"",""Impasse na negociação de cláusulas Econômicas"",""Impasse na negociação de cláusulas sociais"",""Impasse na negociação da cláusula Domingos"",""Impasse na negociação da cláusula Feriados"",""Impasse na negociação da cláusula Contribuição"",""Impasse na negociação da cláusula Banco de Horas"",""Os sindicatos não estão divulgando os impasses da negociação"",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"",""cláusulas em discussão"",""Mandato da diretoria pendente"",""Não há interesse em realizar as negociações por parte do Laboral"",""Não há interesse em realizar as negociações por parte do Patronal"",""Outro""]},{""tipo"":""T"",""texto"":""Caso o motivo seja outro escreva aqui"",""opcoes"":[]},{""tipo"":""T"",""texto"":""Estimativa do reajuste patronal?"",""opcoes"":[]},{""tipo"":""TA"",""texto"":""Observações (Para uso interno da Ineditta)"",""opcoes"":[]}]}'
                                    WHERE id_jfase = 3;
            ");

            migrationBuilder.Sql(@"drop view if exists classe_cnae_vw;");
        }
    }
}
