using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ineditta.Repository.Migrations
{
    /// <inheritdoc />
    public partial class v20 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS jfase_tipodados_perguntas_legendas;");

            migrationBuilder.CreateTable(
                name: "jfase_tipodados_perguntas_legendas",
                columns: table => new
                {
                    idjfase_tipodados_legendas = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    id_tipodado = table.Column<string>(type: "longtext", nullable: false, collation: "utf8mb4_unicode_ci")
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    descricao_tipodado = table.Column<string>(type: "longtext", nullable: false, collation: "utf8mb4_unicode_ci")
                        .Annotation("MySql:CharSet", "utf8mb4")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => x.idjfase_tipodados_legendas);
                })
                .Annotation("MySql:CharSet", "utf8mb4")
                .Annotation("Relational:Collation", "utf8mb4_unicode_ci");

            migrationBuilder.Sql(@"INSERT INTO jfase_tipodados_perguntas_legendas (id_tipodado,descricao_tipodado) VALUES
	                             ('T','Texto'),
	                             ('TA','Texto Longo'),
	                             ('R','Seleção Única (Sim ou Não)'),
	                             ('S','Seleção Única'),
	                             ('SM','Seleção Múltipla'),
	                             ('D','Data');");

            migrationBuilder.Sql(@"TRUNCATE TABLE jfase;");

            migrationBuilder.Sql(@"INSERT INTO jfase (fase) VALUES
	                             ('{""fase"": ""Assembleia Patronal"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": [], ""adicionais"": [{""tipo"": ""D"", ""texto"": ""Data assembléia"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Tipo de assembléia"", ""opcoes"": [""Presencial"", ""Online""]}, {""mask"": ""00:00"", ""tipo"": ""T"", ""texto"": ""Hora da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Endereço da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Empresas que podem participar"", ""opcoes"": [""Todas"", ""Somente associadas""]}, {""tipo"": ""T"", ""texto"": ""Comentários da assembleia patronal"", ""opcoes"": []}]}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""R"", ""texto"": ""Há data prevista para reunião entre entidades sindicais"", ""opcoes"": [], ""adicionais"": [{""tipo"": ""S"", ""texto"": ""Tipo de assembléia"", ""opcoes"": [""Presencial"", ""Online""]}, {""tipo"": ""D"", ""texto"": ""Data assembléia"", ""opcoes"": []}, {""mask"": ""00:00"", ""tipo"": ""T"", ""texto"": ""Hora da assembleia patronal"", ""opcoes"": []}]}, {""tipo"": ""R"", ""texto"": ""Há data prevista para assembleia patronal"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Negociação Não Iniciada"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": [], ""adicionais"": [{""tipo"": ""D"", ""texto"": ""Data assembléia"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Tipo de assembléia"", ""opcoes"": [""Presencial"", ""Online""]}, {""mask"": ""00:00"", ""tipo"": ""T"", ""texto"": ""Hora da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Endereço da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""SM"", ""texto"": ""Endereço da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Comentários da assembleia patronal"", ""opcoes"": []}]}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""TA"", ""texto"": ""Houve alteração no status da negociação?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Em Negociação"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": [], ""adicionais"": [{""tipo"": ""D"", ""texto"": ""Data assembléia"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Tipo de assembléia"", ""opcoes"": [""Presencial"", ""Online""]}, {""mask"": ""00:00"", ""tipo"": ""T"", ""texto"": ""Hora da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Endereço da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""SM"", ""texto"": ""Endereço da assembleia patronal"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Comentários da assembleia patronal"", ""opcoes"": []}]}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""T"", ""texto"": ""Houve alteração no status da negociação?"", ""opcoes"": []}, {""tipo"": ""SM"", ""texto"": ""Em caso de impasse selecione os motivos"", ""opcoes"": ["" "", ""Fechamento do INPC"", ""Mandato Diretoria"", ""Aguardando o fechamento do INPC"", ""Impasse na negociação da cláusula Reajuste salarial"", ""Impasse na negociação de cláusulas Econômicas"", ""Impasse na negociação de cláusulas sociais"", ""Impasse na negociação da cláusula Domingos"", ""Impasse na negociação da cláusula Feriados"", ""Impasse na negociação da cláusula Contribuição"", ""Impasse na negociação da cláusula Banco de Horas"", ""Os sindicatos não estão divulgando os impasses da negociação"", ""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas"", ""cláusulas em discussão"", ""Mandato da diretoria pendente"", ""Não há interesse em realizar as negociações por parte do Laboral"", ""Não há interesse em realizar as negociações por parte do Patronal"", ""Outro""]}, {""tipo"": ""T"", ""texto"": ""Caso o motivo seja outro escreva aqui"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Paralisada"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""T"", ""texto"": ""Motivo da Paralisação?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Dissídio Coletivo"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""mask"": ""0000000-00.0000.0.00.0000"", ""tipo"": ""T"", ""texto"": ""Número do Processo"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Qual região do TRT está sendo julgado?"", ""opcoes"": [""TRT da 1ª Região - Rio de Janeiro"", ""TRT da 2ª Região - São Paulo"", ""TRT da 3ª Região - Minas Gerais"", ""TRT da 4ª Região - Rio Grande do Sul"", ""TRT da 5ª Região - Bahia"", ""TRT da 6ª Região - Pernambuco"", ""TRT da 7ª Região - Ceará"", ""TRT da 8ª Região - Pará e Amapá"", ""TRT da 9ª Região - Paraná"", ""TRT da 10ª Região - Distrito Federal e Tocantins"", ""TRT da 11ª Região - Amazonas e Roraima"", ""TRT da 12ª Região - Santa Catarina"", ""TRT da 13ª Região - Paraíba"", ""TRT da 14ª Região - Acre e Rondônia"", ""TRT da 15ª Região - Sao Paulo/Campinas"", ""TRT da 16ª Região - Maranhão"", ""TRT da 17ª Região - Espírito Santo"", ""TRT da 18ª Região - Goiás"", ""TRT da 19ª Região - Alagoas"", ""TRT da 20ª Região - Sergipe"", ""TRT da 21ª Região - Rio Grande do Norte"", ""TRT da 22ª Região - Piauí"", ""TRT da 23ª Região - Mato Grosso"", ""TRT da 24ª Região - Mato Grosso do Sul""]}, {""tipo"": ""D"", ""texto"": ""Data prevista para audiência"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Houve sentença normativa ou acordão?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Processo transitou em julgado?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Prorrogação CCT"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Fechada"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Fechada Parcialmente"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""R"", ""texto"": ""Foi disponibilizada a Ata/Circular Reajuste Salarial pelos sindicatos?"", ""opcoes"": []}, {""tipo"": ""R"", ""texto"": ""A negociação foi fechada totalmente?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Sem Negociação"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""S"", ""texto"": ""Qual o motivo da paralisação?"", ""opcoes"": [""Aguardando o fechamento do INPC"", ""Impasse na negociação da cláusula Reajuste salarial."", ""Impasse na negociação de cláusulas econômicas."", ""Impasse na negociação de cláusulas sociais."", ""Impasse na negociação da cláusula Domingos."", ""Impasse na negociação da cláusula Feriados."", ""Impasse na negociação da cláusula Contribuição. "", ""Impasse na negociação da cláusula Banco de Horas."", ""Os sindicatos não estão divulgando os impasses da negociação."", ""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas cláusulas em discussão."", ""Mandato da diretoria pendente."", ""Não há interesse em realizar as negociações por parte do Laboral."", ""Não há interesse em realizar as negociações por parte do Patronal."", ""Outros.""]}, {""tipo"": ""T"", ""texto"": ""Se o motivo foi outro, descreva"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'),
	                             ('{""fase"": ""Fechada-formalização documento"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""R"", ""texto"": ""Confirmou o percentual de Reajuste Salarial junto aos dois sindicatos?"", ""opcoes"": []}, {""tipo"": ""R"", ""texto"": ""Verificou se existe circular assinada entre as partes?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Qual o status da disponibilização do documento?"", ""opcoes"": [""Aguardando liberação."", ""Aguardando documento assinado."", ""Aguardando registro no Mediador."", ""Os sindicatos não compartilham uma cópia do documento assinado, somente para associados ou contribuintes."", ""Outros""]}, {""tipo"": ""T"", ""texto"": ""Caso estejam aguardando o mediador informe o Nº da solicitação (MR)"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}');");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "jfase_tipodados_perguntas_legendas");
        }
    }
}
