using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Ineditta.Repository.Migrations
{
    /// <inheritdoc />
    public partial class v79 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                UPDATE jfase SET fase = '{""fase"": ""Dissídio Coletivo"",""perguntas"": [{""tipo"": ""R"",""texto"": ""Contato realizado?"",""opcoes"": [],""adicionais"": [{""tipo"": ""S"",""texto"": ""Sindicato contatado"",""opcoes"": [""Laboral"",""Patronal""]},{""tipo"": ""S"",""texto"": ""Contato feito por"",""opcoes"": [""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""mask"": ""0000000-00.0000.0.00.0000"",""tipo"": ""T"",""texto"": ""Número do Processo"",""opcoes"": []},{""tipo"": ""S"",""texto"": ""Qual região do TRT está sendo julgado?"",""opcoes"": [""TRT da 1ª Região - Rio de Janeiro"",""TRT da 2ª Região - São Paulo"",""TRT da 3ª Região - Minas Gerais"",""TRT da 4ª Região - Rio Grande do Sul"",""TRT da 5ª Região - Bahia"",""TRT da 6ª Região - Pernambuco"",""TRT da 7ª Região - Ceará"",""TRT da 8ª Região - Pará e Amapá"",""TRT da 9ª Região - Paraná"",""TRT da 10ª Região - Distrito Federal e Tocantins"",""TRT da 11ª Região - Amazonas e Roraima"",""TRT da 12ª Região - Santa Catarina"",""TRT da 13ª Região - Paraíba"",""TRT da 14ª Região - Acre e Rondônia"",""TRT da 15ª Região - Sao Paulo/Campinas"",""TRT da 16ª Região - Maranhão"",""TRT da 17ª Região - Espírito Santo"",""TRT da 18ª Região - Goiás"",""TRT da 19ª Região - Alagoas"",""TRT da 20ª Região - Sergipe"",""TRT da 21ª Região - Rio Grande do Norte"",""TRT da 22ª Região - Piauí"",""TRT da 23ª Região - Mato Grosso"",""TRT da 24ª Região - Mato Grosso do Sul""]},{""tipo"": ""D"",""texto"": ""Data prevista para audiência"",""opcoes"": []},{""tipo"": ""T"",""texto"": ""Houve sentença normativa ou acordão?"",""opcoes"": []},{""tipo"": ""T"",""texto"": ""Processo transitou em julgado?"",""opcoes"": []},{""tipo"": ""T"",""texto"": ""Estimativa do reajuste patronal?"",""opcoes"": []},{""tipo"": ""TA"",""texto"": ""Observações (Para uso interno da Ineditta)"",""opcoes"": []}]}]}'
                WHERE id_jfase = 25;

                UPDATE jfase SET fase = '{""fase"": ""Fechada-formalização documento"",""perguntas"": [{""tipo"": ""R"",""texto"": ""Contato realizado?"",""opcoes"": [],""adiconais"": [{""tipo"": ""S"",""texto"": ""Sindicato contatado"",""opcoes"": [""Laboral"",""Patronal""]},{""tipo"": ""S"",""texto"": ""Contato feito por"",""opcoes"": [""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"": ""R"",""texto"": ""Confirmou o percentual de Reajuste Salarial junto aos dois sindicatos?"",""opcoes"": []},{""tipo"": ""R"",""texto"": ""Verificou se existe circular assinada entre as partes?"",""opcoes"": []},{""tipo"": ""S"",""texto"": ""Qual o status da disponibilização do documento?"",""opcoes"": [""Aguardando liberação."",""Aguardando documento assinado."",""Aguardando registro no Mediador."",""Os sindicatos não compartilham uma cópia do documento assinado, somente para associados ou contribuintes."",""Outros""]},{""tipo"": ""T"",""texto"": ""Caso estejam aguardando o mediador informe o Nº da solicitação (MR)"",""opcoes"": []},{""tipo"": ""T"",""texto"": ""Estimativa do reajuste patronal?"",""opcoes"": []},{""tipo"": ""TA"",""texto"": ""Observações (Para uso interno da Ineditta)"",""opcoes"": []}]}]}'
                WHERE id_jfase = 30;

                UPDATE jfase SET fase = '{""fase"": ""Sem Negociação"",""perguntas"": [{""tipo"": ""R"",""texto"": ""Contato realizado?"",""opcoes"": [],""adicionais"": [{""tipo"": ""S"",""texto"": ""Sindicato contatado"",""opcoes"": [""Laboral"",""Patronal""]},{""tipo"": ""S"",""texto"": ""Contato feito por"",""opcoes"": [""E-mail"",""Telefone"",""WhatsApp"",""Facebook"",""Linkedin"",""Twitter"",""Site"",""Fórum"",""Outros""]},{""tipo"": ""S"",""texto"": ""Qual o motivo da paralisação?"",""opcoes"": [""Aguardando o fechamento do INPC"",""Impasse na negociação da cláusula Reajuste salarial."",""Impasse na negociação de cláusulas econômicas."",""Impasse na negociação de cláusulas sociais."",""Impasse na negociação da cláusula Domingos."",""Impasse na negociação da cláusula Feriados."",""Impasse na negociação da cláusula Contribuição. "",""Impasse na negociação da cláusula Banco de Horas."",""Os sindicatos não estão divulgando os impasses da negociação."",""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas cláusulas em discussão."",""Mandato da diretoria pendente."",""Não há interesse em realizar as negociações por parte do Laboral."",""Não há interesse em realizar as negociações por parte do Patronal."",""Outros.""]},{""tipo"": ""T"",""texto"": ""Se o motivo foi outro, descreva"",""opcoes"": []},{""tipo"": ""T"",""texto"": ""Estimativa do reajuste patronal?"",""opcoes"": []},{""tipo"": ""TA"",""texto"": ""Observações (Para uso interno da Ineditta)"",""opcoes"": []}]}]}'
                WHERE id_jfase = 29;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                UPDATE jfase SET fase = '{""fase"": ""Dissídio Coletivo"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""mask"": ""0000000-00.0000.0.00.0000"", ""tipo"": ""T"", ""texto"": ""Número do Processo"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Qual região do TRT está sendo julgado?"", ""opcoes"": [""TRT da 1ª Região - Rio de Janeiro"", ""TRT da 2ª Região - São Paulo"", ""TRT da 3ª Região - Minas Gerais"", ""TRT da 4ª Região - Rio Grande do Sul"", ""TRT da 5ª Região - Bahia"", ""TRT da 6ª Região - Pernambuco"", ""TRT da 7ª Região - Ceará"", ""TRT da 8ª Região - Pará e Amapá"", ""TRT da 9ª Região - Paraná"", ""TRT da 10ª Região - Distrito Federal e Tocantins"", ""TRT da 11ª Região - Amazonas e Roraima"", ""TRT da 12ª Região - Santa Catarina"", ""TRT da 13ª Região - Paraíba"", ""TRT da 14ª Região - Acre e Rondônia"", ""TRT da 15ª Região - Sao Paulo/Campinas"", ""TRT da 16ª Região - Maranhão"", ""TRT da 17ª Região - Espírito Santo"", ""TRT da 18ª Região - Goiás"", ""TRT da 19ª Região - Alagoas"", ""TRT da 20ª Região - Sergipe"", ""TRT da 21ª Região - Rio Grande do Norte"", ""TRT da 22ª Região - Piauí"", ""TRT da 23ª Região - Mato Grosso"", ""TRT da 24ª Região - Mato Grosso do Sul""]}, {""tipo"": ""D"", ""texto"": ""Data prevista para audiência"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Houve sentença normativa ou acordão?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Processo transitou em julgado?"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'
                WHERE id_jfase = 25;

                UPDATE jfase SET fase = '{""fase"": ""Fechada-formalização documento"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""R"", ""texto"": ""Confirmou o percentual de Reajuste Salarial junto aos dois sindicatos?"", ""opcoes"": []}, {""tipo"": ""R"", ""texto"": ""Verificou se existe circular assinada entre as partes?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Qual o status da disponibilização do documento?"", ""opcoes"": [""Aguardando liberação."", ""Aguardando documento assinado."", ""Aguardando registro no Mediador."", ""Os sindicatos não compartilham uma cópia do documento assinado, somente para associados ou contribuintes."", ""Outros""]}, {""tipo"": ""T"", ""texto"": ""Caso estejam aguardando o mediador informe o Nº da solicitação (MR)"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'
                WHERE id_jfase = 30;

                UPDATE jfase SET fase = '{""fase"": ""Sem Negociação"", ""perguntas"": [{""tipo"": ""R"", ""texto"": ""Contato realizado?"", ""opcoes"": []}, {""tipo"": ""S"", ""texto"": ""Sindicato contatado"", ""opcoes"": [""Laboral"", ""Patronal""]}, {""tipo"": ""S"", ""texto"": ""Contato feito por"", ""opcoes"": [""E-mail"", ""Telefone"", ""WhatsApp"", ""Facebook"", ""Linkedin"", ""Twitter"", ""Site"", ""Fórum"", ""Outros""]}, {""tipo"": ""S"", ""texto"": ""Qual o motivo da paralisação?"", ""opcoes"": [""Aguardando o fechamento do INPC"", ""Impasse na negociação da cláusula Reajuste salarial."", ""Impasse na negociação de cláusulas econômicas."", ""Impasse na negociação de cláusulas sociais."", ""Impasse na negociação da cláusula Domingos."", ""Impasse na negociação da cláusula Feriados."", ""Impasse na negociação da cláusula Contribuição. "", ""Impasse na negociação da cláusula Banco de Horas."", ""Os sindicatos não estão divulgando os impasses da negociação."", ""Os sindicatos não estão divulgando os impasses da negociação, por haver muitas cláusulas em discussão."", ""Mandato da diretoria pendente."", ""Não há interesse em realizar as negociações por parte do Laboral."", ""Não há interesse em realizar as negociações por parte do Patronal."", ""Outros.""]}, {""tipo"": ""T"", ""texto"": ""Se o motivo foi outro, descreva"", ""opcoes"": []}, {""tipo"": ""T"", ""texto"": ""Estimativa do reajuste patronal?"", ""opcoes"": []}, {""tipo"": ""TA"", ""texto"": ""Observações (Para uso interno da Ineditta)"", ""opcoes"": []}]}'
                WHERE id_jfase = 29;
            ");
        }
    }
}
